# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: SSMClientToolsSetup@1
- task: SSMSigningToolsSetup@1
- task: DownloadSecureFile@1
  name: SM_CLIENT_CERT_FILE
  inputs:
    secureFile: cert.p12


- task: CmdLine@2
  inputs:
    script: |
      smctl healthcheck
      sudo apt-get install python3-tk 
      pip install -r requirements.txt
      pyinstaller server.spec
      cp '/home/vsts/work/1/s/dist/digi-hrbinger.exe' '$(Build.ArtifactStagingDirectory)'
      
    
  env:
    "SM_HOST": '%SM_HOST%'
    "SM_API_KEY": '%SM_API_KEY%'
    "SM_CLIENT_CERT_PASSWORD": '%SM_CLIENT_CERT_PASSWORD%'
    "SM_CLIENT_CERT_FILE": '$(SM_CLIENT_CERT_FILE.secureFilePath)'


- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop


